Repository DallasFormulaRacing/DataAcquisition2.0, pull requests merged in 2023-12, with the labels that each got.

#146 Minimum implementation of CAN
  Project/DAQ_System/.mxproject
  Project/DAQ_System/.settings/com.st.stm32cube.ide.mcu.sfrview.prefs
  Project/DAQ_System/.settings/language.settings.xml
  Project/DAQ_System/Core/Inc/can.h
  Project/DAQ_System/Core/Inc/stm32f4xx_hal_conf.h
  Project/DAQ_System/Core/Inc/stm32f4xx_it.h
  Project/DAQ_System/Core/Src/can.c
  Project/DAQ_System/Core/Src/main.c
  Project/DAQ_System/Core/Src/stm32f4xx_it.c
  Project/DAQ_System/DAQ_System.ioc
  Project/DAQ_System/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal_can.h
  Project/DAQ_System/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c
  Project/DAQ_System/Program/Src/app.cpp
Labels: feature, CAN

#147 Improvement/106 code docs generation
  .gitignore
  Project/DAQ_System/Program/Src/Sensor/LinearPotentiometer/ilinear_potentiometer.hpp
  Project/DAQ_System/Program/Src/Sensor/LinearPotentiometer/sls1322.cpp
  Project/DAQ_System/Program/Src/Sensor/LinearPotentiometer/sls1322.hpp
  Project/Docs/Dockerfile
  Project/Docs/Doxyfile.in
  Project/Docs/Makefile
  Project/Docs/_static/UPDATED-COLORED-LOGO-DFR-2.png
  Project/Docs/_static/autocross_2023.png
  Project/Docs/_static/breathe.css
  Project/Docs/_static/cropped-Logo-Updated-PNG-1.webp
  Project/Docs/conf.py
  Project/Docs/data_logger/index.rst
  Project/Docs/index.rst
  Project/Docs/linear_potentiometer/index.rst
  Project/Docs/linear_potentiometer/interface.rst
  Project/Docs/linear_potentiometer/sls1322.rst
  Project/Docs/make.bat
  Project/Docs/peripherals/index.rst
  Project/Tests/Dockerfile
Labels: documentation, DevOps & Automation, improvement

#149 extended ID fix
  Project/DAQ_System/Program/Src/app.cpp
Labels: bug, feature, CAN
