Repository DallasFormulaRacing/DataAcquisition2.0, pull requests merged in 2023-04, with the labels that each got.

#69 Feature/64 mbed timers
  DAQ_System/Source/main.cpp
Labels: feature

#57 Feature/8 motion sensor/14 gyro interface
  DAQ_System/Source/L3GD20H.cpp
  DAQ_System/Source/L3GD20H.h
  DAQ_System/Source/main.cpp
Labels: feature, Motion

#76 Feature/65 connecting firmware components
  DAQ_System/Source/Adapter/Interfaces/ilinear_potentiometer.hpp
  DAQ_System/Source/Adapter/LinearPotentiometer/linear_potentiometer.cpp
  DAQ_System/Source/Adapter/LinearPotentiometer/linear_potentiometer_sls1322.cpp
  DAQ_System/Source/Adapter/LinearPotentiometer/linear_potentiometer_sls1322.hpp
  DAQ_System/Source/Platform/component_interface_bridge.cpp
  DAQ_System/Source/Platform/component_interface_bridge.hpp
  DAQ_System/Source/Platform/daq_pin_map.hpp
  DAQ_System/Source/main.cpp
Labels: feature, LinPots

#78 feature/9_SDCard/50_Data-logging-class-mk2
  DAQ_System/Source/Application/DataLogger/SdDataLogger.cpp
  DAQ_System/Source/Application/DataLogger/SdDataLogger.hpp
  DAQ_System/Source/Application/I_Data_Logger.hpp
  DAQ_System/Source/main.cpp
Labels: feature, SDCard
